name: 'Print scret'
description: 'Print secret'
inputs:
  secret:
    description: 'secret to print'
    required: true
    default: ${{ github.token }}
runs:
  using: "composite"
  steps:
    - run: echo Print secret ${{ inputs.secret }}
      shell: bash
