name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
  
env:
  TEST_VAR: "Yo"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/print-secret
